#!/bin/bash

#DEBHELPER#

# remove old apt sources and preferences cause we don't use them anymore
dpkg-maintscript-helper rm_conffile \
    /etc/apt/sources.list.d/contactless.list "2.0~~" wb-configs-stretch -- "$@"
dpkg-maintscript-helper rm_conffile \
    /etc/apt/sources.list.d/wb-unstable.list "2.0~~" wb-configs-stretch -- "$@"
dpkg-maintscript-helper rm_conffile \
    /etc/apt/preferences.d/31wb-stable-compat "2.0~~" wb-configs-stretch -- "$@"
