#!/bin/bash

set -euo pipefail

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
unset TAR_OPTIONS

if (( $# != 0 )); then
    echo "Usage: ${0##*/}" >&2
    exit 2
fi

archive_paths=(/)

if [[ -e /dev/mmcblk0p6 ]]; then
    archive_paths+=(/mnt/data)
fi

exec /usr/bin/tar --one-file-system --create --file - -- "${archive_paths[@]}"
