#!/bin/bash

set -euo pipefail

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
unset TAR_OPTIONS

if (( $# != 0 )); then
    echo "Usage: ${0##*/}" >&2
    exit 2
fi

exec /usr/bin/tar \
    --exclude='/var/tmp' \
    --exclude='/var/log' \
    --exclude='/mnt/data/root/zigbee2mqtt/data/log' \
    --create --file - -- \
    /etc \
    /mnt/data/etc \
    /var \
    /mnt/data/root/zigbee2mqtt/data \
    /mnt/data/makesimple/.SprutHub
