#!/bin/bash

set -euo pipefail

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
unset TAR_OPTIONS

if (( $# != 0 )); then
    echo "Usage: ${0##*/}" >&2
    exit 2
fi

tar_options=(
    --one-file-system
    --directory /
    --exclude='./tmp'
    --exclude='./var/tmp'
)

if [[ ! -e /dev/mmcblk0p6 ]]; then
    tar_options+=(--exclude='./mnt/data')
fi

exec /usr/bin/tar "${tar_options[@]}" --create --file - -- .
