#!/bin/bash

RULES_DST_DIR=/etc/udev/rules.d
RULES_DIR=/usr/share/wb-configs/udev/

# Args:
# - rules file (e.g. "99-wb-uart")
# - suffix (e.g. "wb5")
install_rules() {
	ucf --debconf-ok "$RULES_DIR/$1.rules.$2" "$RULES_DST_DIR/$1.rules"
}

if grep -q "wirenboard,wirenboard-85x" /proc/device-tree/compatible 2>/dev/null; then
    install_rules 99-wb-uart wb85x
    install_rules 99-wb-ethernet wb8xx
elif grep -q "wirenboard,wirenboard-84x" /proc/device-tree/compatible 2>/dev/null; then
    install_rules 99-wb-uart wb84x
    install_rules 99-wb-ethernet wb8xx
elif grep -q "wirenboard,wirenboard-720" /proc/device-tree/compatible 2>/dev/null; then
    install_rules 99-wb-uart wb72
    install_rules 99-wb-ethernet wb72
elif grep -q "wirenboard,wirenboard-670" /proc/device-tree/compatible 2>/dev/null; then
    install_rules 99-wb-uart wb67
    install_rules 99-wb-ethernet wb6
elif grep -q "contactless,imx6ul-wirenboard60" /proc/device-tree/compatible 2>/dev/null; then
    install_rules 99-wb-uart wb6
    install_rules 99-wb-ethernet wb6
elif grep -q "contactless,imx28-wirenboard50" /proc/device-tree/compatible 2>/dev/null; then
    install_rules 99-wb-uart wb5
elif grep -q "contactless,imx23-wirenboard41" /proc/device-tree/compatible 2>/dev/null; then
    install_rules 99-wb-uart wb4
elif grep -q "contactless,imx23-wirenboard32" /proc/device-tree/compatible 2>/dev/null; then
    install_rules 99-wb-uart wb3
elif grep -q "contactless,imx23-wirenboard28" /proc/device-tree/compatible 2>/dev/null; then
    install_rules 99-wb-uart wb2
else
    install_rules 99-wb-uart default
fi

udevadm trigger # apply new udev rules
