#!/bin/bash

. /lib/lsb/init-functions

generate_ssh_host_keys()
{
    log_action_msg "Generating SSH host keys if necessary"
    for keytype in ecdsa ed25519 rsa; do
        log_action_begin_msg "  $keytype"
        local keyfile=/etc/ssh_host_${keytype}_key
        [[ -n "$data_mounted" && -e "/mnt/data/$keyfile" ]] &&
        cp "/mnt/data/${keyfile}" "$keyfile" 2>/dev/null &&
        log_action_cont_msg "from shared partition" &&
        log_action_end_msg $? \
        || {
            [[ -f /etc/ssh/ssh_host_${keytype}_key ]] && {
                log_action_cont_msg " already present, keep it"
                log_action_end_msg $? || return $?
            } || {
                yes | ssh-keygen -f /etc/ssh/ssh_host_${keytype}_key -N '' -t ${keytype} >/dev/null
                log_end_msg $? || return $?
            }
        }
    done
}

# remove obsolete keys
rm -f /etc/ssh/ssh_host_dsa_key*

generate_ssh_host_keys
sync
